param(
  [string]$KeyFile = "key.md",
  [string]$EnvFile = ".env.local"
)

$ErrorActionPreference = "Stop"

function Test-PortFree {
  param([int]$Port)
  $client = New-Object System.Net.Sockets.TcpClient
  try {
    $async = $client.BeginConnect("127.0.0.1", $Port, $null, $null)
    if ($async.AsyncWaitHandle.WaitOne(200)) {
      $client.EndConnect($async)
      return $false
    }
    return $true
  } catch {
    return $true
  } finally {
    $client.Close()
  }
}

function Get-FreePort {
  param([int]$Preferred)
  $port = $Preferred
  while (-not (Test-PortFree -Port $port)) {
    $port++
  }
  return $port
}

function Read-KeyConfig {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "Missing $Path. Put sub2api baseUrl and API key in this file."
  }

  $content = Get-Content -Raw -Encoding UTF8 -LiteralPath $Path
  $chatBaseUrl = $null
  $chatApiKey = $null
  $embeddingBaseUrl = $null
  $embeddingApiKey = $null
  $chatModel = "gpt-5.5"
  $embeddingModel = "text-embedding-3-large"
  $section = "chat"

  foreach ($line in ($content -split "`r?`n")) {
    $trimmed = $line.Trim()
    if (-not $trimmed) { continue }

    $urlMatch = [regex]::Match($trimmed, 'https?://[^\s''"<>]+')
    if ($urlMatch.Success) {
      if ($section -eq "embedding") {
        $embeddingBaseUrl = $urlMatch.Value.Trim().TrimEnd("/")
      } else {
        $chatBaseUrl = $urlMatch.Value.Trim().TrimEnd("/")
      }
      continue
    }

    if ($trimmed -match '^(?i)(apiKey|api_key|api\s*key|key)\s*[:：=]\s*(.+)$') {
      if ($section -eq "embedding") {
        $embeddingApiKey = $Matches[2].Trim()
      } else {
        $chatApiKey = $Matches[2].Trim()
      }
    } elseif ($trimmed -match '^(?i)(chatModel|chat_model|chat\s*model)\s*[:：=]\s*(.+)$') {
      $chatModel = $Matches[2].Trim()
    } elseif ($trimmed -match '^(?i)(embeddingModel|embedding_model|embedding\s*model)\s*[:：=]\s*(.+)$') {
      $embeddingModel = $Matches[2].Trim()
    } elseif ($trimmed -match '(?i)(embedding|向量)') {
      $section = "embedding"
    } elseif ($trimmed -match '(?i)(chat|gpt|通用)') {
      $section = "chat"
    }
  }

  if (-not $chatBaseUrl -or -not $chatApiKey) {
    throw "Could not parse chat baseUrl or API key from $Path."
  }

  if (-not $embeddingBaseUrl) {
    $embeddingBaseUrl = $chatBaseUrl
  }
  if (-not $embeddingApiKey) {
    $embeddingApiKey = $chatApiKey
  }

  return @{
    ChatBaseUrl = $chatBaseUrl.TrimEnd("/")
    ChatApiKey = $chatApiKey
    ChatModel = $chatModel
    EmbeddingBaseUrl = $embeddingBaseUrl.TrimEnd("/")
    EmbeddingApiKey = $embeddingApiKey
    EmbeddingModel = $embeddingModel
  }
}

$config = Read-KeyConfig -Path $KeyFile

$fastgptPort = Get-FreePort 3000
$aiproxyPort = Get-FreePort 3001
$postgresPort = Get-FreePort 5432
$redisPort = Get-FreePort 6379
$mongoPort = Get-FreePort 27017

$envLines = @(
  "# Generated by scripts/local/prepare.ps1. Do not commit.",
  "SUB2API_BASE_URL=$($config.ChatBaseUrl)",
  "SUB2API_API_KEY=$($config.ChatApiKey)",
  "EMBEDDING_BASE_URL=$($config.EmbeddingBaseUrl)",
  "EMBEDDING_API_KEY=$($config.EmbeddingApiKey)",
  "CHAT_MODEL=$($config.ChatModel)",
  "EMBEDDING_MODEL=$($config.EmbeddingModel)",
  "FASTGPT_WEB_PORT=$fastgptPort",
  "AIPROXY_PORT=$aiproxyPort",
  "POSTGRES_PORT=$postgresPort",
  "REDIS_PORT=$redisPort",
  "MONGO_PORT=$mongoPort",
  "FASTGPT_ADMIN_USER=admin001",
  "FASTGPT_ADMIN_PASSWORD=admin001.",
  "PARSE_FILE_WORKERS=1",
  "HTML_TO_MARKDOWN_WORKERS=1"
)

Set-Content -LiteralPath $EnvFile -Encoding UTF8 -Value ($envLines -join "`n")

New-Item -ItemType Directory -Force -Path "runtime", "storage\docs", "storage\images", "storage\web", "storage\videos", "storage\derived", "storage\tmp", "logs" | Out-Null

Write-Output "Prepared $EnvFile"
Write-Output "FastGPT local port: $fastgptPort"
Write-Output "AIProxy local port: $aiproxyPort"
Write-Output "PostgreSQL local port: $postgresPort"
Write-Output "Redis local port: $redisPort"
Write-Output "MongoDB local port: $mongoPort"
