param(
  [string]$EnvFile = ".env.local"
)

$ErrorActionPreference = "Stop"

function Test-PortFree {
  param([int]$Port)
  $client = New-Object System.Net.Sockets.TcpClient
  try {
    $async = $client.BeginConnect("127.0.0.1", $Port, $null, $null)
    if ($async.AsyncWaitHandle.WaitOne(200)) {
      $client.EndConnect($async)
      return $false
    }
    return $true
  } catch {
    return $true
  } finally {
    $client.Close()
  }
}

function Get-FreePort {
  param(
    [int]$Preferred,
    [int[]]$Reserved = @()
  )
  $port = $Preferred
  while ((-not (Test-PortFree -Port $port)) -or ($Reserved -contains $port)) {
    $port++
  }
  return $port
}

$reservedPorts = @()
$fastgptPort = Get-FreePort -Preferred 3000 -Reserved $reservedPorts
$reservedPorts += $fastgptPort
$aiproxyPort = Get-FreePort -Preferred 3001 -Reserved $reservedPorts
$reservedPorts += $aiproxyPort
$mcpPort = Get-FreePort -Preferred 3003 -Reserved $reservedPorts
$reservedPorts += $mcpPort
$minioApiPort = Get-FreePort -Preferred 9000 -Reserved $reservedPorts
$reservedPorts += $minioApiPort
$minioConsolePort = Get-FreePort -Preferred 9001 -Reserved $reservedPorts
$reservedPorts += $minioConsolePort
$postgresPort = Get-FreePort -Preferred 5432 -Reserved $reservedPorts
$reservedPorts += $postgresPort
$redisPort = Get-FreePort -Preferred 6379 -Reserved $reservedPorts
$reservedPorts += $redisPort
$mongoPort = Get-FreePort -Preferred 27017 -Reserved $reservedPorts

$envLines = @(
  "# Generated by scripts/local/prepare.ps1. Do not commit.",
  "FASTGPT_WEB_PORT=$fastgptPort",
  "AIPROXY_PORT=$aiproxyPort",
  "FASTGPT_MCP_PORT=$mcpPort",
  "MINIO_API_PORT=$minioApiPort",
  "MINIO_CONSOLE_PORT=$minioConsolePort",
  "POSTGRES_PORT=$postgresPort",
  "REDIS_PORT=$redisPort",
  "MONGO_PORT=$mongoPort",
  "FASTGPT_ADMIN_USER=admin001",
  "FASTGPT_ADMIN_PASSWORD=admin001.",
  "PARSE_FILE_WORKERS=1",
  "HTML_TO_MARKDOWN_WORKERS=1"
)

Set-Content -LiteralPath $EnvFile -Encoding UTF8 -Value ($envLines -join "`n")

New-Item -ItemType Directory -Force -Path "runtime", "storage\docs", "storage\images", "storage\web", "storage\videos", "storage\derived", "storage\tmp", "logs" | Out-Null
New-Item -ItemType Directory -Force -Path "runtime\fastgpt" | Out-Null

$overridePath = "runtime\fastgpt\docker-compose.local.override.yml"
$overrideLines = @(
  "# Generated by scripts/local/prepare.ps1. Do not commit.",
  "services:",
  "  fastgpt-app:",
  "    environment:",
  "      STORAGE_EXTERNAL_ENDPOINT: http://host.docker.internal:`${MINIO_API_PORT:-9000}",
  "  fastgpt-plugin:",
  "    environment:",
  "      STORAGE_EXTERNAL_ENDPOINT: http://host.docker.internal:`${MINIO_API_PORT:-9000}",
  "  fastgpt-aiproxy:",
  "    ports:",
  "      - `"127.0.0.1:`${AIPROXY_PORT:-3001}:3000`""
)
Set-Content -LiteralPath $overridePath -Encoding UTF8 -Value ($overrideLines -join "`n")

Write-Output "Prepared $EnvFile"
Write-Output "Prepared $overridePath"
Write-Output "FastGPT local port: $fastgptPort"
Write-Output "AIProxy local port: $aiproxyPort"
Write-Output "FastGPT MCP local port: $mcpPort"
Write-Output "MinIO API local port: $minioApiPort"
Write-Output "MinIO console local port: $minioConsolePort"
Write-Output "PostgreSQL local port: $postgresPort"
Write-Output "Redis local port: $redisPort"
Write-Output "MongoDB local port: $mongoPort"
